### ISSUE TITLE
slothana.com has been incorrectly flagged

### ISSUE THREAD

**Issue by SlothanaDev** [phantom/blocklist#1063]
Hi,

Our project's presale page, which is available at https://www.slothana.com/ has been incorrectly flagged as suspicious. It's causing concern for members of our community, and we're eager to get this resolved to help put the mind's of our community members at ease. 

We've already spoken with Blowfish to ensure that their previous incorrect flag was removed, and hope that you can assist us in solving this quickly. 

Thank you very much,
Team Slothana

**Comment by ameerrah** [comment]
Hello, Are you able to fix the page error?

**Comment by pizzaserved** [comment]
any updates on this? I'm not interested in getting the token, just curious if the phantom wallet is right or not (so I can know how much to trust it in the future)

**Comment by Harii94** [comment]
I'm sorry, we will **not** be allowlisting your site. If you have any questions please write to review@blowfish.xyz

**Comment by pizzaserved** [comment]
> I'm sorry, we will **not** be allowlisting your site. If you have any questions please write to [review@blowfish.xyz](mailto:review@blowfish.xyz)

so is it scam or not? what's based on, whether they pay you to get whitelisted or what?
a well-intentioned actor would say "you're blocked because x detected that you did y, and that's a clear sign of fraud". instead, what I'm seeing you say is "we/our partner detected some suspicious activity, but contact us [and maybe pay us and you might get whitelisted]"

**Comment by KaSakee** [comment]
I'd like to see the reason why it's blocked too tbh, not thinking of buying but that's concerning.
