### ISSUE TITLE
S3 URL shouldn't be blocked

### ISSUE THREAD

**Issue by jaidharosenblatt** [phantom/blocklist#593]
s3.amazonaws.com is currently blocked. The specific link is [here](https://bridgesplit-app.s3.amazonaws.com/tokens/sol.png).

![image](https://github.com/phantom/blocklist/assets/47338031/cbbb44b4-c6e8-4f74-a9bc-ac63776a2be1)

**Comment by Chinoman10** [comment]
Agreed. I just tried accessing a PDF document (completely unrelated to crypto even), and I'm faced with this message.
While I understand that AWS's S3 is used for scams as well, these should be reported to Amazon instead of blocked by an extension (or at the very least the file/folder should be blocked, not the entire domain which is used by millions of legitimate businesses).

**Comment by phantomdon** [comment]
Hi folks, thanks for flagging, we've verified this and are working on a solution.

**Comment by phantomdon** [comment]
Hi folks, we just pushed out a fix. Please let us know if the s3 related domains are still getting blocked. Thanks!

**Comment by phantomdon** [comment]
Going to close this, let us know if something like this pops up again!
