### ISSUE TITLE
PWN url blocked, but not in the list

### ISSUE THREAD

**Issue by ashhanai** [phantom/blocklist#837]
Gm, we see that Phantom is blocking our app at app.pwn.xyz which is an official app url. I don't see our domain in the blocklist so I am wondering what is causing it. What can we do to stop flagging our domain as malicious? 

![image (3)](https://github.com/phantom/blocklist/assets/5540689/71c597ab-5c57-427c-991b-a70a07b8a941)

**Comment by mikulas-mrva** [comment]
Since the exact same thing started to pop up with metamask around the same time, [here's a link](https://github.com/MetaMask/eth-phishing-detect/issues/15516) to an issue we have also opened with them in case you are using their `eth-phishing-detect`.

Our twitter: https://twitter.com/pwndao
Linktree with links to discord, founders, and so on: https://linktr.ee/pwndao

**Comment by ashhanai** [comment]
Resolved by removing domain from MM blacklist. Closing this issue.
